services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - static_vol:/app/static
      # - /etc/letsencrypt/:/etc/letsencrypt
      # - /var/www/certbot:/var/www/certbot
    depends_on:
      - web

  web:
    build: .
    command: gunicorn fwphl.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_vol:/app/static
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  static_vol: